### ISSUE TITLE
Issue marked.js

### ISSUE THREAD

**Issue by yveslange** [web-padawan/api-viewer-element#28]
Error when importing and viewing in the browser:

Error compiling: Could not resolve import "marked/lib/marked.esm.js" in "./node_modules/api-viewer-element/lib/lib/markdown.js".

It seems that there is only the marked.js

**Comment by web-padawan** [comment]
Are you using any development server that handles ES modules, like [es-dev-server](https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server)?

If not, you would need one to use this component. The component is using bare module imports, which need a transform in order to run in browser. And `es-dev-server` is doing exactly that.

**Comment by yveslange** [comment]
yes I was using es-dev-server with the node-resolve / watch / followsymlink parameters

**Comment by web-padawan** [comment]
Could you please provide a version that you have installed?  You can check it like this:

```
$ npm list marked
api-viewer-element@0.4.2 /Users/sergey/cf/api-viewer-element
└── marked@0.8.0
```

The `api-viewer-element` depends on [marked 0.8.0](https://github.com/markedjs/marked/releases/tag/v0.8.0) which contains ES module version.

**Comment by web-padawan** [comment]
Starting from `0.5.0` we use a version of marked which has `"module"` entrypoint so it should work. Closing.
