### ISSUE TITLE
Recommended way to style slotted content?

### ISSUE THREAD

**Issue by SPrinss** [web-padawan/api-viewer-element#39]
Say I have a table with rows that have cells. The table has one slot.

```
<template data-element="some-table" data-target="slot">
    <some-table-row>
      <some-table-cell>Data</some-table-cell>
    </some-table-row>
</template>
```

What is the preferred way to style the row and cell? (preferably via an external stylesheet)

Thanks!

**Comment by web-padawan** [comment]
The only currently supported way of styling at the moment is placing a `<style>` tag in template.

Actually, I might consider changing the demo renderer to support "light DOM" option:

1. create a `<slot>` element and append it instead of [appending component](https://github.com/web-padawan/api-viewer-element/blob/ce9f7a44249b58be414863d310426cd732a6e688/src/lib/renderer.ts#L168)
2. append component to the `api-viewer` element itself using `appendChild`.

This would expose component to the outside world so I'm more inclined to make this opt-in feature, rather than enabling it by default. It could be enabled using a boolean attribute.
